/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        surface: '#f5f5f5',
        surfaceSecondary: '#f9f9f9',
        text: '#000000',
        textSecondary: '#666666',
        textTertiary: '#999999',
        border: '#e0e0e0',
        borderLight: '#eaeaea',
        shadow: 'rgba(0,0,0,0.1)',
        card: '#ffffff',
        input: '#f8f8f8',
        placeholder: '#999999',
        error: '#ff4444',
        success: '#00C851',
        warning: '#ffbb33',
        info: '#33b5e5',
        primary: '#007AFF',
        primaryLight: '#E3F2FD',
        accent: '#FF6B6B',
        overlay: 'rgba(0,0,0,0.5)',
        codeBackground: '#F8F8F8',
        selectedBackground: '#F5F5F5',
        inputBackground: '#ffffff',
        chatInputBackground: '#f2f2f7',
        labelBackground: '#ffffff',
        messageBackground: '#f2f2f2',
        inputBorder: '#808080',
        drawerBackground: 'transparent',
        promptButtonBackground: '#E8E8E8',
        promptButtonBorder: '#E8E8E8',
        promptText: '#333333',
        promptSelectedBorder: '#000000',
        promptAddButtonBackground: '#ffffff',
        promptAddButtonBorder: '#666666',
        promptAddText: '#666666',
        promptDeleteBackground: '#666666',
        promptDeleteText: '#ffffff',
        promptScreenInputBorder: '#e0e0e0',
        promptScreenSaveButton: '#007AFF',
        promptScreenSaveButtonText: '#ffffff',
        textDarkGray: '#333333',
        inputToolbarBorder: '#000000',
        fileListBackground: '#ffffff',
        fileItemBorder: '#e0e0e0',
        addButtonBackground: '#f0f0f0',
        chatScreenSplit: '#c7c7c7',
        citationBackground: '#E3F2FD',
        citationText: '#1976D2',
        citationListBackground: '#F5F5F5',
        citationBorder: '#E0E0E0',
        citationBadgeBackground: '#E8E8E8',
        citationBadgeText: '#888888',
      },
    },
  },
  plugins: [],
};
